# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-02 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_wish_granted_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='grant_status',
            field=models.CharField(default='not_granted', max_length=255),
        ),
    ]
