# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-02 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_wish_grant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='user_liked',
            field=models.ManyToManyField(related_name='likes', to='first_app.User'),
        ),
    ]
